global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dickobrazz"
    metrics_path: /metrics
    static_configs:
      - targets: ["dickobrazz:9091"]

  - job_name: "dickobrazz_system"
    metrics_path: /metrics
    static_configs:
      - targets: ["dickobrazz:9100"]
